# The main config file for your Jekyll template

# Site settings
title: Eric Wang               # used for the html title of every page
desc: >
  Studying Computer Science, Class of 2019.

url: http://ericwang.me     # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: ew366@cornell.edu
author: Eric Wang
#twitter_username: clenemt
github_username: derrig
github_source: derrig.github.io

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Articles
    url: /articles/
    desc: Stuff I've written
  - title: Projects
    url: /projects/
    desc: Stuff I've created
  - title: Work
    url: /work/
  - title: About
    url: /about/

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate
